stages:
  - build
  - archive
  
build_project:
  stage: build
  script:
    - xcodebuild clean -workspace TestCI.xcworkspace -scheme TestCI | xcpretty
    - xcodebuild test -workspace TestCI.xcworkspace -scheme TestCI -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.5' | xcpretty -s
  tags:
   - ios-tag
   - version-1.0
archive_build:
  dependencies: []
  stage: archive
  artifacts:
    paths:
      - build/TestCI.ipa
  script:
    - fastlane gym
  tags:
    - ios-tag
    - version-1.0
  only:
    - master
